language: cpp
branches:
  only:
  - master
notifications:
  email: false
git:
  submodules: false
addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt591-trusty
    packages:
    - git
    - g++
    - make
    - autoconf
    - automake
    - libtool
    - cmake
    - pkg-config
    - libxml2-dev
    - libxslt1-dev
    - libzip-dev
    - libsqlite3-dev
    - libusb-1.0-0-dev
    - libssl-dev
    - libssh2-1-dev
    - libcurl4-openssl-dev
    - mesa-common-dev
    - qt59base
    - qt59declarative
    - libqt5x11extras5-dev
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- source /opt/qt59/bin/qt59-env.sh
- qmake --version
script:
- mkdir -p build && cd build
- qmake ./../regif.pro
- make
- ls
- rm -rf Makefile *.cpp *.h *.o .qmake.stash
- ls -lha
deploy:
  provider: releases
  api_key:
    secure: cN1UIPmqQjVBeFsl7Nj0fkq3eFnAWbFmTKYlzXR9Q7s8XNxbRtCwj2GidnbtiCeDL7AS/IAnWq4sjNlWN66b0PlszGeeI5z5BzNA4pW+icrXbumBOlcSWVtREOEfkLYxFAqjO2wILH/VRAUCwZDgiEL9v7tzLWxLMOO36SCm+ajHrNqFFGQN+ubq90WRDieqhgfcgqX4zPyHlV46jd6JOMkqWLTrWqTTnT6FZhancGeE6dBm33hV9D+C33tlbOZ7bMNGf/utPDodAssDNYsbHJpu+NrLM8O6nQCuITu88CRKYaPhMIN/dsIS6NEmGR92vSOnn2At1v9ViFoDwxPAhe1IoqQ3PCUkp4m51cx7C0+StgLqadzNF1rGGetAq8vpgOuZJ77sdCWI3vFiV1oVvm6C2Bz/OQem/ualgE/vnMpYYh/JBMpaG1DwdGm+1Je1ysZNHocrlLEBxUAdDh8A6p1R+QFiwDSDF+vyK10b6zrxPZtfpWxSv2ui0xzbAsT7kE9WNwfU35dXEXr7oyYOCvdpeTX0pxS5kY/dkDG/xjVZ2tg9eP4qPSfjChPyv2bFBwrL2dWJjisCs4Mom1PVku1dBoIodpxF4FRG6fYMLstECdPWJy7TxzrSEwGAjtHXo7jOU1VHrXJgv/jO7aniQa0zurFMNmqRbEqMToApArQ=
  file: "/Users/travis/build/onoie/regif/build/regif.zip"
  on:
    repo: onoie/regif
